// <auto-generated />
using System;
using InfrastructureLayer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfrastructureLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603000001_AlignEntitiesWithDbSchema")]
    partial class AlignEntitiesWithDbSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Entities.Role", b =>
                {
                    b.Property<int>("Id").HasColumnType("integer");
                    b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("Roles");
                    b.HasData(
                        new { Id = 1, Name = "Admin" },
                        new { Id = 2, Name = "HR" },
                        new { Id = 3, Name = "Candidate" });
                });

            modelBuilder.Entity("DomainLayer.Entities.Company", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("LogoUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("WebsiteUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.HasKey("Id");
                    b.HasIndex("Name");
                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DomainLayer.Entities.HRProfile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Bio").HasColumnType("text");
                    b.Property<Guid>("CompanyId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<bool>("IsCompanyVerified").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<string>("JobTitle").HasMaxLength(150).HasColumnType("character varying(150)");
                    b.Property<string>("LinkedInUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("CompanyId");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("HRProfiles");
                });

            modelBuilder.Entity("DomainLayer.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Bio").HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("GithubUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("LinkedInUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<string>("SeniorityLevel").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("TargetRole").HasMaxLength(150).HasColumnType("character varying(150)");
                    b.Property<string[]>("TechStack").IsRequired().HasColumnType("text[]");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AvatarUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("EmailVerificationToken").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("FailedLoginAttempts").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);
                    b.Property<string>("FullName").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("GoogleId").HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<bool>("IsEmailVerified").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<bool>("IsProfileComplete").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<DateTime?>("LockoutUntil").HasColumnType("timestamp with time zone");
                    b.Property<string>("PasswordHash").HasColumnType("text");
                    b.Property<string>("PasswordResetToken").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<DateTime?>("PasswordResetTokenExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<string>("Provider").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("character varying(20)").HasDefaultValue("local");
                    b.Property<string>("RefreshToken").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<DateTime?>("RefreshTokenExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("RoleId").HasColumnType("integer");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("RefreshToken");
                    b.HasIndex("RoleId");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("DomainLayer.Entities.HRProfile", b =>
                {
                    b.HasOne("DomainLayer.Entities.Company", "Company")
                        .WithMany("HRProfiles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("DomainLayer.Entities.HRProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Company");
                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.CandidateProfile", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("DomainLayer.Entities.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.HasOne("DomainLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Role");
                });

            modelBuilder.Entity("DomainLayer.Entities.Company", b =>
                {
                    b.Navigation("HRProfiles");
                });

            modelBuilder.Entity("DomainLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
