// <auto-generated />
using System;
using InfrastructureLayer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfrastructureLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602000002_AddProfilesAndEmailVerification")]
    partial class AddProfilesAndEmailVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Entities.HRProfile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CompanyName").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<bool>("IsCompanyVerified").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<string>("Title").HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("HRProfiles");
                });

            modelBuilder.Entity("DomainLayer.Entities.JobSeekerProfile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ExperienceLevel").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("TargetPosition").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string[]>("TechStack").IsRequired().HasColumnType("text[]");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("JobSeekerProfiles");
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AvatarUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("EmailVerificationToken").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("FailedLoginAttempts").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);
                    b.Property<string>("FullName").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("GoogleId").HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<bool>("IsEmailVerified").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<bool>("IsProfileComplete").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<DateTime?>("LockoutUntil").HasColumnType("timestamp with time zone");
                    b.Property<string>("PasswordHash").HasColumnType("text");
                    b.Property<string>("PasswordResetToken").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<DateTime?>("PasswordResetTokenExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<string>("Provider").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("character varying(20)").HasDefaultValue("local");
                    b.Property<string>("RefreshToken").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<DateTime?>("RefreshTokenExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("RefreshToken");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("DomainLayer.Entities.HRProfile", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("DomainLayer.Entities.HRProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.JobSeekerProfile", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("DomainLayer.Entities.JobSeekerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
