// <auto-generated />
using InfrastructureLayer.Database;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InfrastructureLayer.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260618120000_AddHrNoteAndJdInputToQuestionGenerationJobs")]
partial class AddHrNoteAndJdInputToQuestionGenerationJobs
{
    /// <inheritdoc />
    protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
    }
}
